/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import logic.TypeResource;
import logic.UnitOfMeasure;

/**
 *
 * @author user
 */
public class JPanelTableResource extends javax.swing.JPanel {

    /**
     * Creates new form JPanelTableResource
     */
    public JPanelTableResource() {
        this.parents = (JFrameVentanaPrincipal) parents;
//        initComponents();
        
        String nomcols[] = {"Nombre", "Tipo de Recurso", "Unidad de Media"};
        Object datos[][] = new Object[1][3];
        datos[0][0] = "";
        datos[0][1] = TypeResource.ELEMENT;
        datos[0][2] = UnitOfMeasure.CENTIMETERS;

        defaultTableModel = new DefaultTableModel(datos, nomcols);
        jTableAddRecipes = new JTable(defaultTableModel);

        TypeResource typeResourceOp[] ={TypeResource.ELEMENT,TypeResource.INGREDIENT,TypeResource.TIME};
        typeResource = new JComboBox<TypeResource>(typeResourceOp);
        TableColumn col2 = jTableAddRecipes.getColumnModel().getColumn(1);
        col2.setCellEditor(new DefaultCellEditor(typeResource));
        
        UnitOfMeasure unitOfMeasureOp[] = {UnitOfMeasure.CENTIMETERS,UnitOfMeasure.CUBIC_CENTIMETERS,UnitOfMeasure.GRAM,UnitOfMeasure.MINUTES,UnitOfMeasure.UNIT};
        unitOfMeasure = new JComboBox<UnitOfMeasure>(unitOfMeasureOp);
        TableColumn col = jTableAddRecipes.getColumnModel().getColumn(2);
        col.setCellEditor(new DefaultCellEditor(unitOfMeasure));
        
//        jPanel1.add(new JButton(""));
//        jPanel_add_rect.add(new JButton("zxcvzxc"));
        JScrollPane scroll=new JScrollPane(jTableAddRecipes);
        add(scroll);
//        jButton_guarda_rec.addActionListener(this.parents.getEvento());
//        jButton_guarda_rec.setActionCommand("jButton_agregar_rec");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAddRecipes = new javax.swing.JTable();

        jTableAddRecipes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableAddRecipes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAddRecipes;
    // End of variables declaration//GEN-END:variables

    private JFrameVentanaPrincipal parents = null;
//    private JTable jTable_resources;
    private JComboBox<TypeResource> typeResource;
    private JComboBox<UnitOfMeasure> unitOfMeasure;
    private DefaultTableModel defaultTableModel;

    public DefaultTableModel getDefaultTableModel() {
        return defaultTableModel;
    }

    public JTable getjTable1() {
        return jTableAddRecipes;
    }
    
}
